### ISSUE TITLE
USB support

### ISSUE THREAD

**Issue by vinayak19th** [globaledgesoft/AIML-DashCam-App#7]
Any idea how to link a USB camera using the camera2API into this app

**Comment by rakesh-sankar** [comment]
Need to  call `PackageManager.hasSystemFeature` with the constant `FEATURE_CAMERA_EXTERNAL` to check if your device supports external cameras, if it returns "true" means that your device supports the feature to enable the USB camera through camera2API.

Otherwise use the third party libraries to achieve this.
